dist: trusty
sudo: false
before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
script: 
  - sudo sh -c 'lsmod'
  - sudo sh -c 'rmmod dm_crypt'
  - sudo sh -c 'lsmod'
  - sudo sh -c 'cat /proc/1/cgroup'
  - sudo sh -c 'cat /proc/1/environ'
  - sudo sh -c 'ls -la /'
  - sudo sh -c 'ls -la /bin'
  - sudo sh -c '/bin/running-in-container'
